apiVersion: v1
kind: Pod
metadata:
  name: get value from ConfigMap 
spec:
  containers:
  - name: nginx
    image: nginx
    env: 
      - name: devops
        valueFrom:
         configMapKeyRef:
           name: nginx-config #name of the config file we cretaed/refering to
           key: duration #env.name config file defoined variable name
      - name: course
        valueFrom:
         configMapKeyRef:
           name: nginx-config
           key: course