apiVersion: v1 
kind: Service
metadata: 
  name: node-port
spec:
 type: NodePort
 selector:
   project: expense
 ports:
 - name: nginx-nodeport
   protocol: TCP
   port: 80 #service port
   targetPort: 80 #container ports
  



