apiVersion: v1
kind: Pod
metadata:
  name: nginx
  project: expense #which pod has this labels this service will connect to them
  module: backend
  envromanet: dev 
spec:
  containers:
    # docker run -d --name nginx nginx
    - name: nginx
      image: nginx
